// -----------------------------------------------------------
// Author: Jason Cruz
// Copyright: (c) 2026 AvertXAI. All Rights Reserved.
// Project: AvertXAI Focal Registry
// Description: GENERATED FILE — DO NOT EDIT BY HAND. Short keys for icons.focalregistry.com,
//              emitted by modules/vault/seed/generate-icon-keys.mjs alongside the server's own
//              icon-keys.json, so client and API can never disagree about what a key means.
//              A request reads /i/<key>, so a log or a proxy sees an opaque code instead of the
//              name of a company in someone's vault. That is OBFUSCATION, NOT ENCRYPTION — the
//              map ships in the client and is reversible by anyone who cares to.
// License: Proprietary / Unauthorized copying of this file is strictly prohibited
// File: src/modules/vault/iconKeys.generated.ts
//------------------------------------------------------------

/** dashboard-icons slug → short key. 75 entries. */
export const ICON_KEYS: ReadonlyArray<readonly [string, string]> = [
  ["1password", "xr"],
  ["adobe", "qs"],
  ["amazon", "mg"],
  ["apple", "45"],
  ["asana", "pe"],
  ["aws", "7x"],
  ["azure", "3w"],
  ["backblaze", "4d"],
  ["bitbucket", "je"],
  ["bitwarden", "i4"],
  ["cloudflare", "vq"],
  ["costco", "c9"],
  ["discord", "b4"],
  ["docker", "xi"],
  ["dropbox", "xz"],
  ["ebay", "wx"],
  ["facebook", "73"],
  ["figma", "53"],
  ["github", "as"],
  ["gitlab", "7y"],
  ["gmail", "zm"],
  ["godaddy", "rh"],
  ["google", "58"],
  ["google-drive", "wy"],
  ["hetzner", "jk"],
  ["hulu", "ej"],
  ["icloud", "ak"],
  ["instagram", "88"],
  ["jellyfin", "i2"],
  ["keepass", "kr"],
  ["lastpass", "fh"],
  ["linkedin", "es"],
  ["linode", "aq"],
  ["mailchimp", "xp"],
  ["microsoft", "99"],
  ["microsoft-office", "7i"],
  ["namecheap", "my"],
  ["netflix", "vp"],
  ["netlify", "2g"],
  ["nextcloud", "cb"],
  ["nodejs", "b9"],
  ["notion", "ty"],
  ["npm", "zy"],
  ["paypal", "re"],
  ["pinterest", "xw"],
  ["playstation", "s7"],
  ["plex", "rp"],
  ["porkbun", "85"],
  ["proton", "g7"],
  ["reddit", "q2"],
  ["robinhood", "2x"],
  ["shopify", "ku"],
  ["signal", "sb"],
  ["slack", "h6"],
  ["snapchat", "ua"],
  ["spotify", "m2"],
  ["squarespace", "nr"],
  ["steam", "9j"],
  ["stripe", "mp"],
  ["synology", "qj"],
  ["telegram", "9a"],
  ["tiktok", "5q"],
  ["twitch", "dk"],
  ["twitter", "vu"],
  ["ups", "fv"],
  ["venmo", "k4"],
  ["vercel", "ii"],
  ["verizon", "kn"],
  ["wetransfer", "hr"],
  ["whatsapp", "nc"],
  ["wordpress", "ze"],
  ["x", "pt"],
  ["xbox", "zt"],
  ["youtube", "eg"],
  ["zoom", "u5"],
];
