/* Author: Jason Cruz | (c) 2026 AvertXAI | Proprietary */
// CLAUDE.md standard skeleton — the fixed section set every template starts from, plus the AvertXAI
// house content (embedded snapshot of <repo root>/CLAUDE.md, parsed by ##/### headings) so "Load
// AvertXAI Standard" works even if that file is absent later. DATA ONLY — no IO here.
import type { TemplateSection } from "../../shared/types";

interface StandardSection {
  heading: string;
  level: 1 | 2 | 3;
  guidance: string;
  standard: string; // the matching AvertXAI CLAUDE.md content ("" = no match, keep placeholder)
}

export const STANDARD_SECTIONS: readonly StandardSection[] = [
  {
    heading: "CLAUDE.md",
    level: 1,
    guidance: "One-line description of the file/repo.",
    standard: "This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository.",
  },
  {
    heading: "Git",
    level: 2,
    guidance: "Special git rules (e.g. never add a Claude co-author to commits).",
    standard:
      '**Never add a Claude co-author to commits.** No `Co-Authored-By: Claude`, no "Generated with Claude Code" lines — plain commit messages only. This applies to every commit in this repo.',
  },
  {
    heading: "What this is",
    level: 2,
    guidance: "Exactly what this application is (the What).",
    standard:
      "**RunBooks** — an AvertXAI Electron desktop app built on the platform baseplate generated by `avertxai-mission-control` (the MissionControl skeleton). It is a shell (top bar + flyout nav + Home/Settings/Data Viewer) with empty module slots to be filled in: **Vault** (locked, own DB).",
  },
  {
    heading: "Commands",
    level: 2,
    guidance: "Strict terminal/bash commands Claude may run.",
    standard: `\`\`\`bash
npm install       # postinstall rebuilds better-sqlite3 against Electron — required or the app won't start
npm run dev       # build (vite + esbuild) then launch Electron
npm run dev:diag  # same, with DIAG=1 → runtime render/perf collector active
npm run build     # production build; must be clean
npm run package   # electron-builder --win (nsis + portable) → release/
\`\`\`

No test suite or linter is configured.`,
  },
  {
    heading: "Architecture",
    level: 2,
    guidance: "Technologies + structure of the app.",
    standard: `Electron three-layer split, enforced strictly:

1. **\`electron/core/services/\`** — main-process business logic and the ONLY place SQLite is touched. This is the shared platform spine (renamed from the historic \`timetracker/\` path). Currently holds \`db/\` (connection registry + schema helpers), \`dataviewer/\` (read-only introspection), \`firstrun/\` (setup wizard), and \`utils/\`.
2. **\`electron/\`** — main process (\`main.ts\`), preload (\`preload.ts\` exposes \`window.runbooks\`; the side-effect import of \`core/preload.ts\` exposes \`window.api\`), and thin IPC handlers (\`core/ipc.ts\`) that just delegate to service functions.
3. **\`src/\`** — React 19 renderer, UI-only. Reaches the main process exclusively through \`window.api\`; never touches the DB directly. \`sandbox: true\`, \`contextIsolation: true\`, \`nodeIntegration: false\` — keep it that way.`,
  },
  {
    heading: "Database",
    level: 3,
    guidance: "DB best practices / schema conventions.",
    standard: `- Boot routing: \`platform_registry.db\` under Electron \`userData\` ([electron/core/services/db/registry.ts](electron/core/services/db/registry.ts)) holds the \`orgs\` table; the active org decides which org-scoped files boot — shared DB \`<app_slug>_<org_id>.db\`, vault \`vault_<org_id>.locked.db\`. No active org → no org DBs; the First-Run wizard creates and activates one.
- Connections open via \`openDb(path, name)\` — a name-keyed connection registry in [electron/core/services/db/index.ts](electron/core/services/db/index.ts). \`getDb()\` returns the shared handle.
- **Every table** is created with \`createTable(db, name, columns)\` so all tables share the standard columns: \`id INTEGER PRIMARY KEY\`, \`uuid TEXT UNIQUE NOT NULL\` (generate with \`generateUUIDv7()\` from [electron/core/services/utils/uuidv7.ts](electron/core/services/utils/uuidv7.ts)), \`created_at\`, \`updated_at\` (bump to \`CURRENT_TIMESTAMP\` on every UPDATE).
- WAL + foreign keys ON via pragmas on every connection.
- IPC args arrive as \`unknown\`; the dataviewer service whitelists table names against \`sqlite_master\` and clamps limit/offset — follow that pattern for any new channel that takes renderer input.`,
  },
  {
    heading: "Filling a module slot",
    level: 3,
    guidance: "How to extend the app; flexible/optional section.",
    standard:
      "Each slot under `src/modules/<slug>/` renders a placeholder. To make one real: replace the component body, add service logic under `electron/core/services/<slug>/`, register IPC channels in `ipc.ts`, expose them in `core/preload.ts`. The renderer mount points already exist in `src/App.tsx` (View union, `LEAF` label, conditional mount) and `src/components/Flyout.tsx` (nav button).",
  },
  {
    heading: "Vault encryption",
    level: 3,
    guidance: "How the DB/secrets are encrypted at rest.",
    standard:
      "`vault_<org_id>.locked.db` is SQLCipher-encrypted at rest via envelope encryption: a safeStorage-wrapped per-org secret (`vault_<org_id>.key`) stretched through Argon2id with a fixed salt — see [src/modules/vault/LOCK-ME-DOWN.md](src/modules/vault/LOCK-ME-DOWN.md) and [electron/core/services/vault/crypto.ts](electron/core/services/vault/crypto.ts). The KDF salt must never change (a different salt bricks existing vaults). Value-level encryption of sensitive fields is still open as a second layer.",
  },
  {
    heading: "Conventions",
    level: 2,
    guidance: "House conventions — headers, naming, .nb, etc.",
    standard: `- **Proprietary header on every new \`.ts\`/\`.tsx\` file** — AvertXAI block (Author: Jason Cruz / (c) 2026 AvertXAI / Proprietary). Copy from any existing source file; the one-line form (\`/* Author: Jason Cruz | (c) 2026 AvertXAI | Proprietary */\`) is also accepted.
- **\`.nb\` = not-built**: controls that aren't wired yet get the \`nb\` class; a capture-phase listener in \`App.tsx\` flashes them orange and swallows the click. Use it instead of dead buttons.
- No CSS framework — all styling is hand-rolled global CSS in \`src/globals.css\`. Dark theme background token \`#0d1320\` — kept in sync with \`BG\` in \`electron/main.ts\` (frameless window + titleBarOverlay must match edge-to-edge).
- All external links open via \`shell.openExternal\`; in-app navigation and window opens are denied in \`main.ts\` — don't loosen this.
- Diagnostics (\`electron/diag.ts\`, \`src/diag.ts\`) are dev-gated no-ops unless \`DIAG=1\`; leave the \`bumpRender\` calls in place.
- Desktop-only at a fixed working width; responsive/mobile is not a concern.`,
  },
];

/** Fresh skeleton — empty bodies, guidance as placeholders. */
export function skeletonSections(): TemplateSection[] {
  return STANDARD_SECTIONS.map((s) => ({ heading: s.heading, level: s.level, body: "", fixed: true, guidance: s.guidance }));
}

/** Skeleton pre-filled with the AvertXAI house content (sections without a match keep ""). */
export function standardSections(): TemplateSection[] {
  return STANDARD_SECTIONS.map((s) => ({ heading: s.heading, level: s.level, body: s.standard, fixed: true, guidance: s.guidance }));
}

/** Assemble the ordered sections into flat markdown; empty non-intro sections are skipped. */
export function assembleBody(sections: TemplateSection[]): string {
  const parts: string[] = [];
  for (const s of sections) {
    const body = s.body.trim();
    if (s.level === 1) {
      // The intro title line always ships (a CLAUDE.md must open with its # heading).
      parts.push(body ? `# ${s.heading}\n\n${body}` : `# ${s.heading}`);
      continue;
    }
    if (body === "" || s.heading.trim() === "") continue;
    parts.push(`${"#".repeat(s.level)} ${s.heading}\n\n${body}`);
  }
  return parts.join("\n\n") + "\n";
}
